package utils;
import webdsl.generated.templates.*;public class Statistics{
public static void logStatistics(){
java.util.List<PageStats> results=new java.util.ArrayList<PageStats>();
results.add(new PageStats().setPage("root").setReadOnly(RootPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(RootPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(RootPage.renderWithUpdates.getAndSet(0)).setActionFailed(RootPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(RootPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(RootPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("RemoveSongs").setReadOnly(RemoveSongsPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(RemoveSongsPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(RemoveSongsPage.renderWithUpdates.getAndSet(0)).setActionFailed(RemoveSongsPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(RemoveSongsPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(RemoveSongsPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("RemoveSetlists").setReadOnly(RemoveSetlistsPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(RemoveSetlistsPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(RemoveSetlistsPage.renderWithUpdates.getAndSet(0)).setActionFailed(RemoveSetlistsPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(RemoveSetlistsPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(RemoveSetlistsPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("pagenotfound").setReadOnly(PagenotfoundPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(PagenotfoundPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(PagenotfoundPage.renderWithUpdates.getAndSet(0)).setActionFailed(PagenotfoundPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(PagenotfoundPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(PagenotfoundPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("loginService").setReadOnly(LoginServicePage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(LoginServicePage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(LoginServicePage.renderWithUpdates.getAndSet(0)).setActionFailed(LoginServicePage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(LoginServicePage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(LoginServicePage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("Live").setReadOnly(LivePage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(LivePage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(LivePage.renderWithUpdates.getAndSet(0)).setActionFailed(LivePage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(LivePage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(LivePage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("getMP3").setReadOnly(GetMP3Page.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(GetMP3Page.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(GetMP3Page.renderWithUpdates.getAndSet(0)).setActionFailed(GetMP3Page.actionFailed.getAndSet(0)).setActionSuccessReadOnly(GetMP3Page.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(GetMP3Page.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("getAvatarURLs").setReadOnly(GetAvatarURLsPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(GetAvatarURLsPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(GetAvatarURLsPage.renderWithUpdates.getAndSet(0)).setActionFailed(GetAvatarURLsPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(GetAvatarURLsPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(GetAvatarURLsPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("Dashboard").setReadOnly(DashboardPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(DashboardPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(DashboardPage.renderWithUpdates.getAndSet(0)).setActionFailed(DashboardPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(DashboardPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(DashboardPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("accessDenied").setReadOnly(AccessDeniedPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(AccessDeniedPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(AccessDeniedPage.renderWithUpdates.getAndSet(0)).setActionFailed(AccessDeniedPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(AccessDeniedPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(AccessDeniedPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("AddSetListModal").setReadOnly(AddSetListModalPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(AddSetListModalPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(AddSetListModalPage.renderWithUpdates.getAndSet(0)).setActionFailed(AddSetListModalPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(AddSetListModalPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(AddSetListModalPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("AddSongModal").setReadOnly(AddSongModalPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(AddSongModalPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(AddSongModalPage.renderWithUpdates.getAndSet(0)).setActionFailed(AddSongModalPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(AddSongModalPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(AddSongModalPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("EditSetListModalSetList").setReadOnly(EditSetListModalSetListPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(EditSetListModalSetListPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(EditSetListModalSetListPage.renderWithUpdates.getAndSet(0)).setActionFailed(EditSetListModalSetListPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(EditSetListModalSetListPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(EditSetListModalSetListPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("EditSongModalSong").setReadOnly(EditSongModalSongPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(EditSongModalSongPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(EditSongModalSongPage.renderWithUpdates.getAndSet(0)).setActionFailed(EditSongModalSongPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(EditSongModalSongPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(EditSongModalSongPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("LoginPlaceholder").setReadOnly(LoginPlaceholderPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(LoginPlaceholderPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(LoginPlaceholderPage.renderWithUpdates.getAndSet(0)).setActionFailed(LoginPlaceholderPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(LoginPlaceholderPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(LoginPlaceholderPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("noMessages").setReadOnly(NoMessagesPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(NoMessagesPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(NoMessagesPage.renderWithUpdates.getAndSet(0)).setActionFailed(NoMessagesPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(NoMessagesPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(NoMessagesPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("RegisterPlaceholder").setReadOnly(RegisterPlaceholderPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(RegisterPlaceholderPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(RegisterPlaceholderPage.renderWithUpdates.getAndSet(0)).setActionFailed(RegisterPlaceholderPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(RegisterPlaceholderPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(RegisterPlaceholderPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("showMessagesLStringL").setReadOnly(ShowMessagesLStringLPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(ShowMessagesLStringLPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(ShowMessagesLStringLPage.renderWithUpdates.getAndSet(0)).setActionFailed(ShowMessagesLStringLPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(ShowMessagesLStringLPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(ShowMessagesLStringLPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("slSearchString_Placeholder").setReadOnly(SlSearchString_PlaceholderPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(SlSearchString_PlaceholderPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(SlSearchString_PlaceholderPage.renderWithUpdates.getAndSet(0)).setActionFailed(SlSearchString_PlaceholderPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(SlSearchString_PlaceholderPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(SlSearchString_PlaceholderPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("songSearchString_Placeholder_Bool_Bool").setReadOnly(SongSearchString_Placeholder_Bool_BoolPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(SongSearchString_Placeholder_Bool_BoolPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(SongSearchString_Placeholder_Bool_BoolPage.renderWithUpdates.getAndSet(0)).setActionFailed(SongSearchString_Placeholder_Bool_BoolPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(SongSearchString_Placeholder_Bool_BoolPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(SongSearchString_Placeholder_Bool_BoolPage.actionSuccessWithUpdates.getAndSet(0)));
results.add(new PageStats().setPage("userSearchUser_String_Placeholder").setReadOnly(UserSearchUser_String_PlaceholderPage.renderReadOnly.getAndSet(0)).setReadOnlyFromCache(UserSearchUser_String_PlaceholderPage.renderReadOnlyFromCache.getAndSet(0)).setWithUpdates(UserSearchUser_String_PlaceholderPage.renderWithUpdates.getAndSet(0)).setActionFailed(UserSearchUser_String_PlaceholderPage.actionFailed.getAndSet(0)).setActionSuccessReadOnly(UserSearchUser_String_PlaceholderPage.actionSuccessReadOnly.getAndSet(0)).setActionSuccessWithUpdates(UserSearchUser_String_PlaceholderPage.actionSuccessWithUpdates.getAndSet(0)));
utils.PageStats.printList(results);
}
}
